[[redirects]]
  from = "https://requests.janschoepp.com/*" 
  to = "https://jangerhard-overseerr.cloud.seedboxes.cc/:splat"
  status = 200
  headers = {X-From = "Netlify"}
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
    NODE_VERSION = "15"
