[[redirects]]
  from = "https://requests.janschoepp.com/*" 
  to = "https://jangerhard-overseerr.cloud.seedboxes.cc"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
    NODE_VERSION = "15"
